---

- name: Backup show version and other user-level commands
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: Run multiple commands on remote nodes
      ios_command:
        commands:
          - show version
          - ping 8.8.8.8

      register: print_output

    - debug: var=print_output.stdout_lines

    - name: Save output to a file
      copy:
        content: "{{ print_output.stdout[0] }}"
        dest: "./output/{{ inventory_hostname }}.txt"
