---

- name: Get ARP information
  hosts: all
  gather_facts: false

  tasks:
    - name: Running show arp ...
      raw: "show arp"

      register: print_output

    - name: ARP Table of devices
      debug: var=print_output.stdout_lines
