---

- hosts: all
  gather_facts: false
  pre_tasks:
  
  - name: Test reachability to the internet
    ios_ping:
      dest: "8.8.8.8"

  - name: Retrieve Running-Config
    ios_facts:
      gather_subset: 
        - config

  - name: Copy Running-Config
    copy:
      content: "{{ ansible_net_config }}"
      dest: "./outputs/before_config/{{ ansible_host }}_config"
      backup: yes