---

- name: Opening routers' interfaces
  tags: routers,interface
  ios_interfaces:
    config:
    - name: GigabitEthernet0/1
      enabled: true
      description: "**To-CS1**"

    - name: GigabitEthernet0/2
      enabled: true
      description: "**To-CS2**"

    - name: Loopback0
      enabled: true
      description: "**Loop0**"

- tags: routers,l3interface,ip
  block:
  - name: Configuring L3 interfaces
    ios_l3_interfaces:
      config:
      - name: GigabitEthernet0/1
        ipv4:
        - address: 172.16.1.0/31
      - name: GigabitEthernet0/2
        ipv4:
        - address: 172.16.2.0/31
      - name: Loopback0
        ipv4:
        - address: 1.1.1.1/32
      state: replaced
  rescue:
  - name: Defaulting interfaces
    ios_l3_interfaces:
      config:
      - name: GigabitEthernet0/1
      - name: GigabitEthernet0/2
      - name: Loopback0
      state: deleted

  - name: Reconfigurating interfaces
    ios_l3_interfaces:
      config:
      - name: GigabitEthernet0/1
        ipv4:
        - address: 172.16.1.0/31
      - name: GigabitEthernet0/2
        ipv4:
        - address: 172.16.2.0/31
      - name: Loopback0
        ipv4:
        - address: 1.1.1.1/32
      state: replaced

- name: Configuring OSPFv2
  tags: routers,ospf,routing,dynamic
  cisco.ios.ios_ospfv2:
    config:
      processes:
      - process_id: 1
        network:
          - address: 172.16.0.0
          - wildcard_bits: 0.0.3.255
          - area: '0'
        passive_interfaces:
          interface:
            set_interface: true
            name:
              - Loopback0
              - GigabitEthernet0/0
        router_id: 1.1.1.1
    state: replaced

  # notify: restart_ospfv2
